<h1>Activity 0: Introduction to NumPy</h1>

<h2>Introduction</h2>

<p>This activity aims to introduce you to Numpy - a package for scientific computing with Python that we will use extensively in this class. This activity is by no means a complete tutorial on NumPy but it should be enough for you to do most of projects and activities in this class. For more information, please see NumPy's <a href="https://docs.scipy.org/doc/numpy/user/quickstart.html">official tutorial</a> and <a href='https://docs.scipy.org/doc/numpy/reference/index.html'>API</a>. To use NumPy, first import the package as what we do in the following cell:</p>

In [1]:
import numpy as np

<h2>Creating Vectors and Matrices</h2>

<p> NumPy's main object is a multidimensional array, in other words, a table of the same data type. Let's see an example on how to create an NumPy array:  </p>

In [6]:
X = np.array([[1,2,3], [4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In the cell above, we created a two dimensional table, a.k.a, a matrix of size $2 \times 3$. To create an array, what you need to do is to pass in a list of objects into the function [np.array()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html). Now that we have shown you how to create a matrix, you might have wondered how we can represent a vector in NumPy. There are three ways to represent a vector in NumPy. In the cell below we are using the function [.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) to specify the length of the 2-D array in each dimension.

In [3]:
v1=np.array([3,4,5])
print("This is a numpy vector:{}. It's shape is {}".format(v1, v1.shape))
v2=v1.reshape((3,1))
print("This is a column vector (matrix):\n{}. It's shape is {}".format(v2, v2.shape))
v3=v1.reshape((1,3))
print("This is a row vector (matrix):{}. It's shape is {}".format(v3,v3.shape))

This is a numpy vector:[3 4 5]. It's shape is (3,)
This is a column vector (matrix):
[[3]
 [4]
 [5]]. It's shape is (3, 1)
This is a row vector (matrix):[[3 4 5]]. It's shape is (1, 3)


<p><p>These three representation are usually not compatible. Some operations will still work, but not in the way we expect. </p> We will always prefer the vector notation. You can transform any (matrix) vector into a numpy vector with [.flatten()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html).</p>

In [7]:
#We add v1 and v2 but the output is not as expected
v4=v2+v1
print('The sum of a column vector and numpy vector:\n{}'.format(v4))
v5 = v2.flatten() + v1
print('The expected result of summing two numpy vectors: {}'.format(v5))

The sum of a column vector and numpy vector:
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]
The expected result of summing two numpy vectors: [ 6  8 10]


<h3> Attributes of Numpy Arrays </h3>

Three important attributes of NumPy array are [.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html), [.ndim](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html), and [.size](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html): 

In [8]:
# the shape of an array
print("The shape of X: {}".format(X.shape))

# the dimension of an array
print("The dimension of X: {}".format(X.ndim))

#total number of elements of an array
print("The size of X: {}".format(X.size))

The shape of X: (2, 3)
The dimension of X: 2
The size of X: 6


<h3>Common Arrays</h3>

There are also functions for creating common matrices such as [eye()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html), [zeros()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html), and [arange()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html). Eye() creates an identity matrix, zero() creates a matrix of all zeros, and arange() creates a vector of equally spaced values.

In [9]:
print('Identity matrix of length 3:\n {}'.format(np.eye(3)))
print('Zero matrix of shape 2 by 3:\n {}'.format(np.zeros([2,3])))
print('Vector incrementing by 2 each element:\n {}'.format(np.arange(1,11,2)))

Identity matrix of length 3:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Zero matrix of shape 2 by 3:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]
Vector incrementing by 2 each element:
 [1 3 5 7 9]


<h2>Matrix Operations</h2>
<p>In this section we will cover matrix functions that you will find useful in future projects. In many instances rather than writing functions from scratch there will be preexisting numpy functions which are faster and will save you time.</p> 

In [19]:
# Create some matrices
X = np.array([[1,2], [3,4]])
Y = np.array([[5,6], [7,8]])
A = np.array([[1,2,3,4], [7,8,9,10]])
B = np.array([[4,5,6,7], [1,2,3,4]])

To perform matrix multiplication use [np.dot()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) or the @ symbol. Using the traditional Python multiplication will multiply the values of the matrix element-wise.

In [20]:
print('X: \n{}'.format(X))
print('Y: \n{}'.format(Y))
print('Element-wise multiplication:\n{}'.format(X*Y))
print('Matrix multiplication:\n{}'.format(np.dot(X,Y)))
print('Alternative syntax for matrix multiplication:\n{}'.format(X @ Y))

X: 
[[1 2]
 [3 4]]
Y: 
[[5 6]
 [7 8]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
Alternative syntax for matrix multiplication:
[[19 22]
 [43 50]]


To tranpose a matrix use [.transpose()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html). An alternative and more concise syntax is .T. 

In [21]:
print('B transposed:\n', B.transpose())
print('Alternative syntax for transpose:\n', B.T)

B transposed:
 [[4 1]
 [5 2]
 [6 3]
 [7 4]]
Alternative syntax for transpose:
 [[4 1]
 [5 2]
 [6 3]
 [7 4]]


### Exercise 1

<p>Use NumPy to calculate $AB^T-Y$. The output should be: $[[ 55,  24],
       [185,  82]]$</p>

In [22]:
###INSERT CODE HERE###

<h3>Other matrix operations </h3>

Other useful functions to use in your projects are [np.amax()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html#numpy.amax), [np.amin()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.amin.html), [np.argmax()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html), and [np.argmin()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html). Note that with all of these functions we can specify the axis along which we want to perform the operation. If no axis is specified the above functions will perform the operation across all dimensions.

In [28]:
print('X:\n{}'.format(X))

#Using amax and amin
print('Largest element in X: {}'.format(np.amax(X)))
print('Largest elements along the first axis: {}'.format(np.amax(X, axis = 0)))
print('Smallest element in X: {}'.format(np.amin(X)))
print('Smallest elements along the second axis: {}'.format(np.amin(X, axis = 1)))

X:
[[1 2]
 [3 4]]
Largest element in X: 4
Largest elements along the first axis: [3 4]
Smallest element in X: 1
Smallest elements along the second axis: [1 3]


In [27]:
#Using argmax and argmin
print('Index of the smallest element in X: {}'.format(np.argmin(X)))
print('Indices of the largest elements along the first axis: {}'.format(np.argmin(X, axis = 0)))

Index of the smallest element in X: 0
Indices of the largest elements along the first axis: [0 0]


Another function you will find helpful is [np.sum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html). Like with np.amax, np.amin, etc. we can specify the axis along which to sum. 

In [25]:
print('Sum of all elements in X: {}'.format(np.sum(X)))
print('Sum of elements along the first axis: {}'.format(np.sum(X, axis = 0)))

Sum of all elements in X: 10
Sum of elements along the first axis: [4 6]


[Vstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html) and [hstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html) are useful for adding columns or rows to existing matrices.

In [26]:
print('A: \n{}'.format(A))
print('B: \n{}'.format(B))

print('Vertical stacking concatenates vectors along the first axis:\n{}'.format(np.vstack((A,B))))
print('Horizontal stacking concatenates vectors along the second axis:\n{}'.format(np.hstack((A,B))))

A: 
[[ 1  2  3  4]
 [ 7  8  9 10]]
B: 
[[4 5 6 7]
 [1 2 3 4]]
Vertical stacking concatenates vectors along the first axis:
[[ 1  2  3  4]
 [ 7  8  9 10]
 [ 4  5  6  7]
 [ 1  2  3  4]]
Horizontal stacking concatenates vectors along the second axis:
[[ 1  2  3  4  4  5  6  7]
 [ 7  8  9 10  1  2  3  4]]


### Exercise 2

<p> Find the maximum elements in A along the first axis (axis = 0) and add it to the sum of elements in B along the first axis. Your output should be:</p>
**array([12, 15, 18, 21])** </p>

In [ ]:
###INSERT CODE HERE###

<h3>Element-wise Matrix Operations</h3>

There are many operations that you might want to perform such as taking the square root or exponent on each element of a numpy array. Some examples of these functions are [np.exp()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.exp.html), [np.sqrt()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html), and [np.square()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.square.html). There are many more numpy functions that will perform element-wise operations on numpy arrays so make sure to look them up in the official documentation.

In [108]:
X = np.arange(1,6,1)
print('X: {}'.format(X))
print('The exponential applied element-wise to X: \n{}'.format(np.exp(X)))
print('The square root applied element-wise to X: \n{}'.format(np.sqrt(X)))
print('The square applied element-wise to X: \n{}'.format(np.square(X)))

X: [1 2 3 4 5]
The exponential applied element-wise to X: 
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591 ]
The square root applied element-wise to X: 
[ 1.          1.41421356  1.73205081  2.          2.23606798]
The square applied element-wise to X: 
[ 1  4  9 16 25]


<h2>Indexing and Slicing</h2>
<p>NumPy's array can indexed and sliced, just like python's list. For single dimension array operations: </p>

In [29]:
x1 = np.arange(5)

print("x1: {}".format(x1))
print("Indexing a single element: {}".format(x1[3]))
print("Slicing: {}".format(x1[1:3]))  
print("Slicing last two numbers: {}".format(x1[-2:]))


x1: [0 1 2 3 4]
Indexing a single element: 3
Slicing: [1 2]
Slicing last two numbers: [3 4]


<h3> Multidimensional arrays:</h3>

In [30]:
x2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("x2:\n{}".format(x2))
print("Full slice:\n{}".format(x2[::])) 
print("Indexing an element at the first row, third column: {}".format(x2[0,2]))
print("Slicing on both axes:\n{}".format(x2[1:,:2]))
print("Indexing by row:{}".format(x2[0])) # Selecting the first row 
print("Indexing by column: {}".format(x2[:,0])) # Selecting the first column

print("Iterating through each row in a matrix:")
for row in x2:
    print(row)

x2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Full slice:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Indexing an element at the first row, third column: 3
Slicing on both axes:
[[4 5]
 [7 8]]
Indexing by row:[1 2 3]
Indexing by column: [1 4 7]
Iterating through each row in a matrix:
[1 2 3]
[4 5 6]
[7 8 9]


### Exercise 3

<p>Return the first and second row of A then the second and third column of A. </p>

In [ ]:
###INSERT CODE HERE###